name: CI

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches:
      - main
      - '*'
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 
            -"16"
            -"18" # Latest two versions of Node.js

      - name: Install dependencies
        run: npm install
